import { useEffect, useRef, useState } from 'react';
import { useNavigate, useParams, Link } from 'react-router-dom';
import { deletePortfolioItem, getPortfolioItem, getStoredToken } from '../api';
import { generateA4PdfFromElement } from '../utils/pdfGenerator';
import Button from '../components/ui/Button.jsx';
import PageShell from '../components/ui/PageShell.jsx';
import Alert from '../components/ui/Alert.jsx';
import ConfirmDialog from '../components/ui/ConfirmDialog.jsx';

export default function PortfolioView() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [item, setItem] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [pdfLoading, setPdfLoading] = useState(false);
  const [pdfError, setPdfError] = useState('');
  const [confirmDelete, setConfirmDelete] = useState(false);
  const isAuthenticated = Boolean(getStoredToken());
  const containerRef = useRef(null);

  useEffect(() => {
    getPortfolioItem(id)
      .then((data) => {
        if (data?.error) {
          setError(data.error);
          setItem(null);
        } else {
          setItem(data);
        }
      })
      .catch(() => setError('Gagal memuat data'))
      .finally(() => setLoading(false));
  }, [id]);

  const handleDelete = async () => {
    const token = getStoredToken();
    const res = await deletePortfolioItem(id, token);
    if (res?.success) navigate('/app/portfolios');
  };

  if (loading) {
    return (
      <PageShell>
        <div className="h-80 animate-pulse rounded-xl bg-white/[0.06]" />
      </PageShell>
    );
  }
  if (!item) {
    return (
      <PageShell className="space-y-4">
        <Alert tone="error">{error || 'Tidak ditemukan'}</Alert>
        <Button type="button" onClick={() => navigate('/app/portfolios')}>
          Kembali ke daftar
        </Button>
      </PageShell>
    );
  }

  return (
    <PageShell
      title={item.title}
      description="Preview item portfolio dan export sebagai PDF bila diperlukan."
      className="space-y-6 pb-24"
      actions={
        <>
          <Button
            type="button"
            onClick={async () => {
              if (!containerRef.current) return;
              try {
                setPdfError('');
                setPdfLoading(true);
                await generateA4PdfFromElement(containerRef.current, {
                  filename: `portfolio-item-${id}.pdf`,
                  header: item.title || 'Portfolio Item',
                  footer: 'Generated by Portfolio Builder',
                  marginMm: 20,
                  pixelRatio: 2,
                  quality: 0.85,
                  useCORS: true,
                  backgroundColor: '#ffffff',
                });
              } catch {
                setPdfError('Gagal generate PDF.');
              } finally {
                setPdfLoading(false);
              }
            }}
            disabled={pdfLoading}
          >
            {pdfLoading ? 'Membuat PDF...' : 'PDF'}
          </Button>
          {isAuthenticated && (
            <>
              <Button as={Link} to={`/app/portfolios/${id}/edit`} variant="secondary">
                Edit
              </Button>
              <Button type="button" onClick={() => setConfirmDelete(true)} variant="danger">
                Hapus
              </Button>
            </>
          )}
        </>
      }
    >
      <div ref={containerRef} className="space-y-6">
        {pdfError && <Alert tone="error">{pdfError}</Alert>}
        {item.image_url || item.imageUrl ? (
          <img
            alt={item.title}
            src={item.image_url || item.imageUrl}
            className="w-full max-w-2xl rounded-lg border border-white/20"
          />
        ) : null}
        <p className="max-w-3xl opacity-90">{item.description}</p>
        {item.project_url || item.projectUrl ? (
          <a
            href={item.project_url || item.projectUrl}
            target="_blank"
            rel="noreferrer"
            className="text-blue-300 underline"
          >
            Lihat Project
          </a>
        ) : null}
      </div>
      <ConfirmDialog
        open={confirmDelete}
        title="Hapus item portfolio?"
        description="Item ini akan dihapus permanen dari koleksi Anda."
        confirmLabel="Hapus"
        danger
        onCancel={() => setConfirmDelete(false)}
        onConfirm={handleDelete}
      />
    </PageShell>
  );
}
